# Generated by Django 5.0.6 on 2024-07-01 07:23

import django.db.models.deletion
import utilisateur.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=50)),
                ('photo_profile', models.ImageField(upload_to=utilisateur.models.renomer_image)),
                ('type_profile', models.CharField(choices=[('eleve', 'eleve'), ('enseignant', 'enseignant'), ('parent', 'parent')], default='eleve', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
