# Generated by Django 5.0.6 on 2024-07-05 15:23

import utilisateur.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo_profile',
            field=models.ImageField(blank=True, upload_to=utilisateur.models.renomer_image),
        ),
    ]
