# Generated by Django 5.0.6 on 2024-07-13 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='fpe',
            field=models.FileField(blank=True, null=True, upload_to='FPE', verbose_name='Une image'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='PDF', verbose_name='Fichier pdf'),
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercice_id', models.CharField(max_length=40, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(max_length=500)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='exercices', verbose_name="Fichier de l'exercice")),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='programme.lesson')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme.matiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme.niveaux')),
            ],
        ),
    ]
