# Generated by Django 5.0.6 on 2024-07-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0002_alter_lesson_fpe_alter_lesson_pdf_exercice'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='exercice',
            field=models.FileField(blank=True, null=True, upload_to='PDF', verbose_name="Fichier d'exercice d'application"),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='fpe',
            field=models.FileField(blank=True, null=True, upload_to='FPE', verbose_name='Une image du cours'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='PDF', verbose_name='Fichier pdf du cours'),
        ),
        migrations.DeleteModel(
            name='Exercice',
        ),
    ]
